"""Deterministic run engine (§15, 06-T1..T4).

Work graph: one execution item per (case, repetition), and one evaluation item per
(execution, metric binding) that depends on it. The orchestration loop owns all scheduling:

- bounded concurrency: at most `concurrency.application` executions and
  `concurrency.evaluation` evaluations in flight; nothing else is materialized as a task;
- single writer: one SQLite connection, used only on this event-loop thread; work-item
  transitions and run events are written by this loop, attempt records by the service
  calls it awaits — commits are synchronous and never interleave;
- crash-consistent ordering: an item is marked `running` (with its attempt number) before
  dispatch, the attempt record is committed, then the item moves on. Every transition is a
  compare-and-set, so a stale or duplicate transition cannot overwrite a newer one;
- budgets are reserved before dispatch and reconciled after (BudgetLedger);
- retries only as `retry.classify_*` allow, with seeded backoff; unknown effects stop;
- run control: pause stops new dispatch and lets in-flight work finish; cancel stops
  dispatch and cancels in-flight work (recorded as cancelled); interrupt stops dispatch,
  records in-flight outcomes and leaves unfinished work pending for `resume`. A second
  interrupt also aborts in-flight work, but unfinished work still stays resumable: an
  aborted effect-free execution returns to pending, an ambiguous effectful one becomes
  `unknown_effect`;
- the session holds the run's lease (see `services.runs`) and heartbeats it; if the lease
  is lost, the session stops dispatching as if interrupted.
"""

from __future__ import annotations

import asyncio
import heapq
import itertools
import random
import time
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from aibench.core.models import (
    BenchmarkCase,
    EffectState,
    ErrorKind,
    ExecutionResult,
    ExecutionStatus,
    UsageEvent,
    UsageRole,
    WorkItemState,
)
from aibench.core.plans import ExecutablePlan
from aibench.engine.budget import BudgetLedger
from aibench.engine.retry import backoff_delay, classify_evaluation, classify_execution
from aibench.registry import ResolvedMetric
from aibench.runners.base import BaseRunner
from aibench.services.execution import invoke_and_record
from aibench.services.scoring import BindingScorer, MissingExecution
from aibench.storage.artifacts import ArtifactStore
from aibench.storage.repositories import Storage

TERMINAL = frozenset(
    {
        WorkItemState.SUCCEEDED,
        WorkItemState.FAILED,
        WorkItemState.BLOCKED,
        WorkItemState.CANCELLED,
        WorkItemState.UNKNOWN_EFFECT,
    }
)
_POLL_SECONDS = 0.1
_HEARTBEAT_SECONDS = 2.0


class RunState(str, Enum):
    CREATED = "created"
    RUNNING = "running"
    PAUSING = "pausing"
    PAUSED = "paused"
    CANCELLING = "cancelling"
    INTERRUPTING = "interrupting"
    COMPLETED = "completed"
    BUDGET_EXHAUSTED = "budget_exhausted"
    CANCELLED = "cancelled"
    INTERRUPTED = "interrupted"


def execution_key(case_id: str, repetition: int) -> str:
    return f"exec:{case_id}:r{repetition}"


def evaluation_key(case_id: str, repetition: int, binding_hash: str) -> str:
    return f"eval:{case_id}:r{repetition}:{binding_hash[7:23]}"


def parse_work_item_key(task_key: str, kind: str) -> tuple[str, int, str | None]:
    """Decode a work key while allowing colons in a dataset's case ID.

    The repetition and binding suffixes are generated by the harness, so parse them from
    the right edge instead of treating every colon as a delimiter.
    """
    prefix = {"execution": "exec:", "evaluation": "eval:"}.get(kind)
    if prefix is None or not task_key.startswith(prefix):
        raise ValueError(f"invalid {kind} work-item key: {task_key!r}")
    body = task_key[len(prefix) :]
    binding_key: str | None = None
    if kind == "evaluation":
        try:
            body, binding_key = body.rsplit(":", 1)
        except ValueError as exc:
            raise ValueError(f"invalid {kind} work-item key: {task_key!r}") from exc
    try:
        case_id, repetition_text = body.rsplit(":r", 1)
        if not case_id or not repetition_text.isdecimal():
            raise ValueError
        return case_id, int(repetition_text), binding_key
    except ValueError as exc:
        raise ValueError(f"invalid {kind} work-item key: {task_key!r}") from exc


class RunController:
    """Internal run control (06-T4) for commands now and the chat layer later. Methods are
    called on the event loop; `request(...)` is safe from other threads (signal handlers),
    and requests made before the engine starts are applied when it does.

    `cancelled` means the run is cancelled: unstarted work is recorded as cancelled.
    `abort_event` aborts in-flight invocations and evaluations; cancel sets it, and so does
    a second interrupt, which still leaves unstarted work pending for resume."""

    def __init__(self) -> None:
        self.state = RunState.CREATED
        self.abort_event = asyncio.Event()
        self._wake = asyncio.Event()
        self.cancelled = False
        self.interrupting = False
        self.paused = False
        self._loop: asyncio.AbstractEventLoop | None = None
        self._early: list[str] = []

    def bind(self, loop: asyncio.AbstractEventLoop) -> None:
        self._loop = loop
        early, self._early = self._early, []
        for action in early:
            getattr(self, action)()

    def pause(self) -> None:
        if not self.cancelled and not self.interrupting:
            self.paused = True
            self._wake.set()

    def resume(self) -> None:
        self.paused = False
        self._wake.set()

    def cancel(self) -> None:
        self.cancelled = True
        self.abort_event.set()
        self.paused = False
        self._wake.set()

    def interrupt(self) -> None:
        """First call: stop dispatch, let in-flight work finish, keep the rest resumable.
        A second call also aborts in-flight work; unfinished work stays resumable."""
        if self.interrupting:
            self.abort_event.set()
        self.interrupting = True
        self.paused = False
        self._wake.set()

    @property
    def stopping(self) -> bool:
        return self.cancelled or self.interrupting

    def request(self, action: str) -> None:
        if self._loop is None:
            self._early.append(action)  # a signal during setup: applied on bind
        else:
            self._loop.call_soon_threadsafe(getattr(self, action))

    async def wait_for_change(self, timeout: float) -> None:
        self._wake.clear()
        try:
            await asyncio.wait_for(self._wake.wait(), timeout)
        except TimeoutError:
            pass


@dataclass
class _Item:
    task_key: str
    kind: str  # "execution" | "evaluation"
    case_id: str
    repetition: int
    attempt: int
    binding_hash: str | None = None


@dataclass
class RunOutcome:
    state: RunState
    counts: dict[str, dict[str, int]]
    budget: dict[str, Any]
    stop_reason: str | None = None


@dataclass
class RunEngine:
    storage: Storage
    artifacts: ArtifactStore
    run_id: str
    plan: ExecutablePlan
    runner: BaseRunner | None  # None when no execution work remains (e.g. resume)
    cases: dict[str, BenchmarkCase]
    metrics: list[ResolvedMetric]
    scoring_id: str
    ledger: BudgetLedger
    controller: RunController
    rng: random.Random
    heartbeat: Callable[[], bool] = lambda: True  # refresh the run lease; False if lost
    _exec_queue: deque[_Item] = field(default_factory=deque)
    _eval_queue: deque[_Item] = field(default_factory=deque)
    _delayed: list[tuple[float, int, _Item]] = field(default_factory=list)
    _in_flight: dict[asyncio.Task[Any], _Item] = field(default_factory=dict)
    _waiting_evals: dict[str, list[_Item]] = field(default_factory=dict)  # by execution key
    _executions: dict[str, ExecutionResult | None] = field(default_factory=dict)
    _exec_states: dict[str, WorkItemState] = field(default_factory=dict)
    _scorers: dict[str, BindingScorer] = field(default_factory=dict)
    _reserved: set[str] = field(default_factory=set)
    _seq: itertools.count[int] = field(default_factory=itertools.count)
    _stop_reason: str | None = None
    _last_heartbeat: float = field(default_factory=time.monotonic)
    _session_started: float = field(default_factory=time.monotonic)
    warnings: list[str] = field(default_factory=list)

    # ------------------------------------------------------------------ setup

    def _event(self, event_type: str, **payload: Any) -> None:
        self.storage.append_run_event(self.run_id, event_type, payload)

    def _transition(
        self,
        item: _Item,
        from_states: set[WorkItemState],
        to: WorkItemState,
        *,
        attempt: int | None = None,
        error: str | None = None,
    ) -> bool:
        updated = self.storage.transition_work_item(
            self.run_id,
            item.task_key,
            from_states=from_states,
            to_state=to,
            attempt=attempt,
            last_error=error,
        )
        if updated is None:
            return False
        self._event(
            "item_state",
            task_key=item.task_key,
            state=to.value,
            attempt=updated.attempt,
            reason=error,
        )
        return True

    def _load(self) -> None:
        by_binding = {m.binding_hash[7:23]: m.binding_hash for m in self.metrics}
        items = self.storage.list_work_items(self.run_id)
        executions: dict[str, ExecutionResult] = {}
        for e in self.storage.list_execution_attempts(self.run_id):
            key = execution_key(e.case_id, e.repetition_id)
            if key not in executions or e.attempt_id > executions[key].attempt_id:
                executions[key] = e
        order = {case_id: i for i, case_id in enumerate(self.cases)}
        pending_evals: list[_Item] = []
        for w in sorted(items, key=lambda w: w.task_key):
            case_id, repetition, binding_key = parse_work_item_key(w.task_key, w.kind)
            item = _Item(
                w.task_key,
                w.kind,
                case_id,
                repetition,
                w.attempt,
                by_binding.get(binding_key) if binding_key else None,
            )
            if w.kind == "execution":
                self._exec_states[w.task_key] = w.state
                self._executions[w.task_key] = executions.get(w.task_key)
                if w.state is WorkItemState.PENDING:
                    self._exec_queue.append(item)
            elif w.state is WorkItemState.PENDING:
                pending_evals.append(item)
        self._exec_queue = deque(
            sorted(self._exec_queue, key=lambda i: (order.get(i.case_id, 0), i.repetition))
        )
        for item in sorted(
            pending_evals, key=lambda i: (order.get(i.case_id, 0), i.repetition, i.task_key)
        ):
            if self._exec_states.get(execution_key(item.case_id, item.repetition)) in TERMINAL:
                self._eval_queue.append(item)
            else:
                self._waiting_evals.setdefault(
                    execution_key(item.case_id, item.repetition), []
                ).append(item)

    # ------------------------------------------------------------------ main loop

    async def execute(self) -> RunOutcome:
        self.controller.bind(asyncio.get_running_loop())
        self._load()
        self._set_state(RunState.RUNNING)
        self._event(
            "run_session_started",
            pending_executions=len(self._exec_queue),
            pending_evaluations=len(self._eval_queue) + sum(map(len, self._waiting_evals.values())),
        )
        needs_runner = bool(self._exec_queue)
        try:
            if needs_runner:
                assert self.runner is not None, "execution work remains but no runner was given"
                await self.runner.prepare()
            await self._open_scorers()
            await self._loop()
        finally:
            await self._shutdown(needs_runner)
        return self._finish()

    async def _open_scorers(self) -> None:
        wanted = {i.binding_hash for i in self._eval_queue} | {
            i.binding_hash for items in self._waiting_evals.values() for i in items
        }
        for metric in self.metrics:
            if metric.binding_hash in wanted:
                scorer = BindingScorer(
                    self.storage,
                    self.artifacts,
                    self.scoring_id,
                    metric,
                    self.plan.evaluation_timeout_seconds,
                    self.controller.abort_event,
                )
                await scorer.open()
                self._scorers[metric.binding_hash] = scorer

    def _keep_lease(self) -> None:
        now = time.monotonic()
        if now - self._last_heartbeat < _HEARTBEAT_SECONDS:
            return
        self._last_heartbeat = now
        if not self.heartbeat() and not self.controller.interrupting:
            self.warnings.append("run lease lost to another session; stopped dispatching")
            self.controller.interrupt()

    async def _loop(self) -> None:
        ctl = self.controller
        while True:
            self._keep_lease()
            if ctl.cancelled:
                self._drain_delayed()  # waiting retries are cancelled, not stranded
            self._release_due_retries()
            stopping = ctl.stopping
            if not stopping and not ctl.paused:
                self._dispatch_executions()
            if not ctl.paused:
                await self._dispatch_evaluations(stopping)
            if self._in_flight:
                self._set_state(self._busy_state())
                done, _ = await asyncio.wait(
                    set(self._in_flight),
                    timeout=self._next_wait(),
                    return_when=asyncio.FIRST_COMPLETED,
                )
                for task in done:
                    await self._complete(task, self._in_flight.pop(task))
                continue
            # Nothing in flight.
            if ctl.paused and not stopping:
                self._set_state(RunState.PAUSED)
                await ctl.wait_for_change(_POLL_SECONDS * 5)
                continue
            if self._delayed and not stopping:
                await ctl.wait_for_change(self._next_wait())
                continue
            if self._settle_undispatchable(stopping):
                continue  # newly unblocked evaluations to record
            if not self._eval_queue:
                return

    def _busy_state(self) -> RunState:
        ctl = self.controller
        if ctl.cancelled:
            return RunState.CANCELLING
        if ctl.interrupting:
            return RunState.INTERRUPTING
        return RunState.PAUSING if ctl.paused else RunState.RUNNING

    def _next_wait(self) -> float:
        if not self._delayed:
            return _POLL_SECONDS
        return max(0.0, min(_POLL_SECONDS, self._delayed[0][0] - time.monotonic()))

    def _drain_delayed(self) -> None:
        while self._delayed:
            _, _, item = heapq.heappop(self._delayed)
            (self._exec_queue if item.kind == "execution" else self._eval_queue).append(item)

    def _release_due_retries(self) -> None:
        now = time.monotonic()
        while self._delayed and self._delayed[0][0] <= now:
            _, _, item = heapq.heappop(self._delayed)
            (self._exec_queue if item.kind == "execution" else self._eval_queue).appendleft(item)

    # ------------------------------------------------------------------ dispatch

    def _dispatch_executions(self) -> None:
        while self._exec_queue and self._running("execution") < self.plan.concurrency.application:
            if self._stop_reason is not None:
                return
            denial = self.ledger.reserve_application()
            if denial is not None:
                self._stop_reason = denial
                self._event("budget_exhausted", reason=denial)
                return
            item = self._exec_queue.popleft()
            item.attempt += 1
            if not self._transition(
                item, {WorkItemState.PENDING}, WorkItemState.RUNNING, attempt=item.attempt
            ):
                self.ledger.settle_application(dispatched=False, cost=None)
                continue
            assert self.runner is not None
            task = asyncio.ensure_future(
                invoke_and_record(
                    self.runner,
                    self.cases[item.case_id],
                    storage=self.storage,
                    artifacts=self.artifacts,
                    run_id=self.run_id,
                    repetition_id=item.repetition,
                    attempt_id=item.attempt,
                    cancel=self.controller.abort_event,
                )
            )
            self._in_flight[task] = item

    async def _dispatch_evaluations(self, stopping: bool) -> None:
        if stopping and not self.controller.cancelled:
            return  # interrupt: unstarted evaluations stay pending for resume
        while self._eval_queue and self._running("evaluation") < self.plan.concurrency.evaluation:
            item = self._eval_queue.popleft()
            assert item.binding_hash is not None
            scorer = self._scorers[item.binding_hash]
            exec_key = execution_key(item.case_id, item.repetition)
            execution = self._executions.get(exec_key)
            exec_state = self._exec_states.get(exec_key)
            needs_evaluator = exec_state is WorkItemState.SUCCEEDED and execution is not None
            if needs_evaluator and self.controller.cancelled:
                self._record_without_evaluator(item, scorer, "cancelled", ExecutionStatus.CANCELLED)
                continue
            if needs_evaluator:
                denial = self.ledger.reserve_evaluation()
                if denial is not None:
                    if self._stop_reason is None:
                        self._stop_reason = denial
                        self._event("budget_exhausted", reason=denial)
                    self._record_without_evaluator(item, scorer, f"not_evaluated:{denial}")
                    continue
                self._reserved.add(item.task_key)
            item.attempt += 1
            if not self._transition(
                item, {WorkItemState.PENDING}, WorkItemState.RUNNING, attempt=item.attempt
            ):
                self._release_evaluation(item)
                continue
            if execution is None:
                self._finish_missing(
                    item, scorer, f"not_executed:{(exec_state or WorkItemState.BLOCKED).value}"
                )
                continue
            task = asyncio.ensure_future(scorer.score(execution, [self.cases[item.case_id]]))
            self._in_flight[task] = item

    def _running(self, kind: str) -> int:
        return sum(1 for i in self._in_flight.values() if i.kind == kind)

    def _release_evaluation(self, item: _Item) -> None:
        if item.task_key in self._reserved:
            self._reserved.discard(item.task_key)
            self.ledger.settle_evaluation(None)

    def _record_without_evaluator(
        self,
        item: _Item,
        scorer: BindingScorer,
        reason: str,
        status: ExecutionStatus = ExecutionStatus.SKIPPED,
    ) -> None:
        item.attempt += 1
        if self._transition(
            item, {WorkItemState.PENDING}, WorkItemState.RUNNING, attempt=item.attempt
        ):
            self._finish_missing(item, scorer, reason, status)

    def _finish_missing(
        self,
        item: _Item,
        scorer: BindingScorer,
        reason: str,
        status: ExecutionStatus = ExecutionStatus.SKIPPED,
    ) -> None:
        execution = self._executions.get(execution_key(item.case_id, item.repetition))
        target = MissingExecution(
            self.run_id,
            item.case_id,
            item.repetition,
            execution.execution_id if execution else None,
        )
        result = scorer.score_missing(target, reason, status=status)
        scorer.finalize(result)
        final = (
            WorkItemState.CANCELLED
            if status is ExecutionStatus.CANCELLED
            else WorkItemState.SUCCEEDED
        )
        self._transition(
            item,
            {WorkItemState.RUNNING},
            final,
            error=None if final is WorkItemState.SUCCEEDED else reason,
        )

    # ------------------------------------------------------------------ completion

    async def _complete(self, task: asyncio.Task[Any], item: _Item) -> None:
        if item.kind == "execution":
            await self._complete_execution(task, item)
        else:
            self._complete_evaluation(task, item)

    async def _complete_execution(self, task: asyncio.Task[Any], item: _Item) -> None:
        try:
            result: ExecutionResult = task.result()
        except Exception as exc:  # noqa: BLE001 - an engine-side failure, recorded not raised
            self.ledger.settle_application(dispatched=True, cost=None)
            self._final_execution(
                item, WorkItemState.FAILED, f"engine_error:{type(exc).__name__}: {exc}"[:500], None
            )
            return
        self.ledger.settle_application(dispatched=was_dispatched(result), cost=result.cost)
        if result.cost is not None or result.usage is not None:
            self.storage.commit_usage_event(
                UsageEvent(
                    usage_event_id=f"{result.execution_id}:usage",
                    run_id=self.run_id,
                    role=UsageRole.APPLICATION,
                    provider=None,
                    tokens=result.usage,
                    calls=1,
                    cost=result.cost,
                )
            )
        verdict = classify_execution(result)
        ctl = self.controller
        stopping = ctl.stopping
        if ctl.interrupting and not ctl.cancelled and verdict.final_state is WorkItemState.CANCELLED:
            # Aborted by a second interrupt with no effect possible: effect-free work stays
            # resumable. (An ambiguous effectful abort is UNKNOWN_EFFECT, handled below.)
            self._transition(
                item,
                {WorkItemState.RUNNING},
                WorkItemState.PENDING,
                error="aborted by interrupt; safe to repeat (no effects)",
            )
            return
        if verdict.retry and item.attempt < self.plan.retry.max_attempts:
            if stopping and ctl.cancelled:
                self._final_execution(
                    item,
                    WorkItemState.CANCELLED,
                    f"cancelled before retrying: {verdict.reason}",
                    result,
                )
                return
            delay = backoff_delay(
                self.plan.retry, item.attempt, self.rng, verdict.retry_after_seconds
            )
            if self._transition(
                item, {WorkItemState.RUNNING}, WorkItemState.PENDING, error=verdict.reason
            ):
                self._event(
                    "retry_scheduled",
                    task_key=item.task_key,
                    attempt=item.attempt,
                    delay_seconds=round(delay, 3),
                )
                if stopping:  # interrupt: leave it pending for resume
                    return
                heapq.heappush(self._delayed, (time.monotonic() + delay, next(self._seq), item))
            return
        reason = verdict.reason if verdict.final_state is not WorkItemState.SUCCEEDED else None
        if verdict.retry:
            reason = f"{verdict.reason} (retries exhausted after {item.attempt} attempts)"
        self._final_execution(item, verdict.final_state, reason, result)

    def _final_execution(
        self, item: _Item, state: WorkItemState, reason: str | None, result: ExecutionResult | None
    ) -> None:
        self._transition(item, {WorkItemState.RUNNING}, state, error=reason)
        self._exec_states[item.task_key] = state
        self._executions[item.task_key] = result
        self._eval_queue.extend(self._waiting_evals.pop(item.task_key, []))

    def _complete_evaluation(self, task: asyncio.Task[Any], item: _Item) -> None:
        assert item.binding_hash is not None
        scorer = self._scorers[item.binding_hash]
        try:
            result = task.result()
        except BaseException as exc:  # noqa: BLE001 - includes cancellation of the task
            self._release_evaluation(item)
            status = (
                ExecutionStatus.CANCELLED
                if isinstance(exc, asyncio.CancelledError)
                else ExecutionStatus.ERROR
            )
            self._finish_missing(item, scorer, f"engine_error:{type(exc).__name__}", status)
            return
        if item.task_key in self._reserved:
            self._reserved.discard(item.task_key)
            self.ledger.settle_evaluation(dict(result.resources))
        verdict = classify_evaluation(result, scorer.manifest)
        ctl = self.controller
        if (
            ctl.interrupting
            and not ctl.cancelled
            and (verdict.retry or result.status is ExecutionStatus.CANCELLED)
        ):
            # Interrupted: a transient or aborted evaluation is not a final result; it runs
            # again on resume (its spend stays recorded as an attempt).
            self._transition(
                item, {WorkItemState.RUNNING}, WorkItemState.PENDING, error=verdict.reason
            )
            return
        if verdict.retry and item.attempt < self.plan.retry.max_attempts and not ctl.stopping:
            delay = backoff_delay(self.plan.retry, item.attempt, self.rng)
            if self._transition(
                item, {WorkItemState.RUNNING}, WorkItemState.PENDING, error=verdict.reason
            ):
                self._event(
                    "retry_scheduled",
                    task_key=item.task_key,
                    attempt=item.attempt,
                    delay_seconds=round(delay, 3),
                )
                heapq.heappush(self._delayed, (time.monotonic() + delay, next(self._seq), item))
            return
        scorer.finalize(result)
        reason = None if verdict.final_state is WorkItemState.SUCCEEDED else verdict.reason
        if verdict.retry:
            reason = f"{verdict.reason} (retries exhausted after {item.attempt} attempts)"
        self._transition(item, {WorkItemState.RUNNING}, verdict.final_state, error=reason)

    # ------------------------------------------------------------------ stopping

    def _settle_undispatchable(self, stopping: bool) -> bool:
        """Nothing is in flight. Decide what happens to work that can no longer be
        dispatched; returns True if evaluations were released for recording."""
        if self.controller.interrupting and not self.controller.cancelled:
            self._exec_queue.clear()  # unstarted work stays pending for resume
            self._eval_queue.clear()
            self._delayed.clear()
            return False
        if not self._exec_queue:
            return False
        if self.controller.cancelled:
            state, reason = WorkItemState.CANCELLED, "run cancelled before dispatch"
        elif self._stop_reason is not None:
            state, reason = WorkItemState.BLOCKED, f"budget: {self._stop_reason}"
        else:
            return False
        while self._exec_queue:
            item = self._exec_queue.popleft()
            if self._transition(item, {WorkItemState.PENDING}, state, error=reason):
                self._exec_states[item.task_key] = state
                self._eval_queue.extend(self._waiting_evals.pop(item.task_key, []))
        return True

    async def _shutdown(self, needs_runner: bool) -> None:
        for task in list(self._in_flight):
            task.cancel()
        if self._in_flight:
            await asyncio.gather(*self._in_flight, return_exceptions=True)
        for scorer in self._scorers.values():
            await scorer.close(self.warnings)
        if needs_runner and self.runner is not None:
            await self.runner.close()

    def _set_state(self, state: RunState) -> None:
        if self.controller.state is not state:
            self.controller.state = state
            self.storage.update_run_status(self.run_id, state.value)

    def _finish(self) -> RunOutcome:
        ctl = self.controller
        pending = any(
            w.state in (WorkItemState.PENDING, WorkItemState.RUNNING)
            for w in self.storage.list_work_items(self.run_id)
        )
        if ctl.cancelled:
            state = RunState.CANCELLED
        elif ctl.interrupting or pending:
            state = RunState.INTERRUPTED
        elif self._stop_reason is not None:
            state = RunState.BUDGET_EXHAUSTED
        else:
            state = RunState.COMPLETED
        self._set_state(state)
        counts = work_counts(self.storage, self.run_id)
        budget = self.ledger.summary()
        self._event(
            "run_session_ended",
            state=state.value,
            counts=counts,
            session_elapsed_seconds=round(time.monotonic() - self._session_started, 3),
            budget=budget,
            stop_reason=self._stop_reason,
            warnings=self.warnings,
        )
        return RunOutcome(state, counts, budget, self._stop_reason)


_NEVER_DISPATCHED = frozenset(
    {ErrorKind.BINDING, ErrorKind.REQUEST_LIMIT, ErrorKind.POLICY_DENIED, ErrorKind.SPAWN_FAILED}
)


def was_dispatched(result: ExecutionResult) -> bool:
    """Whether the call reached the application (and so counts against the call budget).
    `effect_state` alone cannot say: effect-free apps report `none_declared` either way."""
    if result.effect_state is EffectState.NOT_DISPATCHED:
        return False
    return result.error_kind not in _NEVER_DISPATCHED


def work_counts(storage: Storage, run_id: str) -> dict[str, dict[str, int]]:
    counts: dict[str, dict[str, int]] = {}
    for item in storage.list_work_items(run_id):
        kind = counts.setdefault(item.kind, {})
        kind[item.state.value] = kind.get(item.state.value, 0) + 1
    return counts
