"""Deterministic run engine (§15, 06-T1..T4).

Work graph: one execution item per (case, repetition), and one evaluation item per
(execution, metric binding) that depends on it. The orchestration loop owns all scheduling:

- bounded concurrency: at most `concurrency.application` executions and
  `concurrency.evaluation` evaluations in flight; nothing else is materialized as a task;
- single writer: one SQLite connection, used only on this event-loop thread; work-item
  transitions and run events are written by this loop, attempt records by the service
  calls it awaits — commits are synchronous and never interleave;
- crash-consistent ordering: an item is marked `running` (with its attempt number) before
  dispatch, the attempt record is committed, then the item moves on. Every transition is a
  compare-and-set, so a stale or duplicate transition cannot overwrite a newer one;
- budgets are reserved before dispatch and reconciled after (BudgetLedger);
- retries only as `retry.classify_*` allow, with seeded backoff; unknown effects stop;
- run control: pause stops new dispatch and lets in-flight work finish; cancel stops
  dispatch and cancels in-flight work (recorded as cancelled); interrupt stops dispatch,
  records in-flight outcomes and leaves unfinished work pending for `resume`. A second
  interrupt also aborts in-flight work, but unfinished work still stays resumable: an
  aborted effect-free execution returns to pending, an ambiguous effectful one becomes
  `unknown_effect`;
- the session holds the run's lease (see `services.runs`) and heartbeats it; if the lease
  is lost, the session stops dispatching as if interrupted.
"""

from __future__ import annotations

import asyncio
import errno
import heapq
import itertools
import random
import sqlite3
import time
from collections import deque
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, TypeVar

from aibench.core.models import (
    ApplicationSpec,
    BenchmarkCase,
    EffectState,
    ErrorKind,
    ExecutionResult,
    ExecutionStatus,
    UsageEvent,
    UsageRole,
    WorkItemState,
)
from aibench.core.plans import ExecutablePlan
from aibench.engine import cache
from aibench.engine.budget import BudgetLedger
from aibench.engine.quota import QuotaGate
from aibench.engine.retry import (
    backoff_delay,
    classify_evaluation,
    classify_execution,
    http_status,
)
from aibench.registry import ResolvedMetric
from aibench.runners.base import BaseRunner, ResetReport, race
from aibench.services.execution import invoke_and_record
from aibench.services.scoring import BindingScorer, MissingExecution, episode_prefixes
from aibench.storage.artifacts import ArtifactStore
from aibench.storage.repositories import RunControlState, Storage

TERMINAL = frozenset(
    {
        WorkItemState.SUCCEEDED,
        WorkItemState.FAILED,
        WorkItemState.BLOCKED,
        WorkItemState.CANCELLED,
        WorkItemState.UNKNOWN_EFFECT,
    }
)
_POLL_SECONDS = 0.1
_CONTROL_POLL_SECONDS = 0.25
_T = TypeVar("_T")
# Evaluations held by a quota that dispatch looks past per pass (bounded work per pass).
_HELD_SCAN = 256
# The runner bounds a reset by its lifecycle timeout; this only waits for an abort.
_RESET_WAIT_SECONDS = 3600.0
_HEARTBEAT_SECONDS = 2.0


class RunState(str, Enum):
    CREATED = "created"
    RUNNING = "running"
    PAUSING = "pausing"
    PAUSED = "paused"
    CANCELLING = "cancelling"
    INTERRUPTING = "interrupting"
    COMPLETED = "completed"
    BUDGET_EXHAUSTED = "budget_exhausted"
    CANCELLED = "cancelled"
    INTERRUPTED = "interrupted"


def execution_key(case_id: str, repetition: int) -> str:
    return f"exec:{case_id}:r{repetition}"


def evaluation_key(case_id: str, repetition: int, binding_hash: str) -> str:
    return f"eval:{case_id}:r{repetition}:{binding_hash[7:23]}"


def parse_work_item_key(task_key: str, kind: str) -> tuple[str, int, str | None]:
    """Decode a work key while allowing colons in a dataset's case ID.

    The repetition and binding suffixes are generated by the harness, so parse them from
    the right edge instead of treating every colon as a delimiter.
    """
    prefix = {"execution": "exec:", "evaluation": "eval:"}.get(kind)
    if prefix is None or not task_key.startswith(prefix):
        raise ValueError(f"invalid {kind} work-item key: {task_key!r}")
    body = task_key[len(prefix) :]
    binding_key: str | None = None
    if kind == "evaluation":
        try:
            body, binding_key = body.rsplit(":", 1)
        except ValueError as exc:
            raise ValueError(f"invalid {kind} work-item key: {task_key!r}") from exc
    try:
        case_id, repetition_text = body.rsplit(":r", 1)
        if not case_id or not repetition_text.isdecimal():
            raise ValueError
        return case_id, int(repetition_text), binding_key
    except ValueError as exc:
        raise ValueError(f"invalid {kind} work-item key: {task_key!r}") from exc


class RunController:
    """Internal run control (06-T4) for commands now and the chat layer later. Methods are
    called on the event loop; `request(...)` is safe from other threads (signal handlers),
    and requests made before the engine starts are applied when it does.

    `cancelled` means the run is cancelled: unstarted work is recorded as cancelled.
    `abort_event` aborts in-flight invocations and evaluations; cancel sets it, and so does
    a second interrupt, which still leaves unstarted work pending for resume."""

    def __init__(self) -> None:
        self.state = RunState.CREATED
        self.abort_event = asyncio.Event()
        self._wake = asyncio.Event()
        self.cancelled = False
        self.interrupting = False
        self.paused = False
        self._loop: asyncio.AbstractEventLoop | None = None
        self._early: list[str] = []

    def bind(self, loop: asyncio.AbstractEventLoop) -> None:
        self._loop = loop
        early, self._early = self._early, []
        for action in early:
            getattr(self, action)()

    def pause(self) -> None:
        if not self.cancelled and not self.abort_event.is_set():
            self.interrupting = False
            self.paused = True
            self._wake.set()

    def resume(self) -> None:
        if self.cancelled or self.abort_event.is_set():
            return
        self.interrupting = False
        self.paused = False
        self._wake.set()

    def cancel(self) -> None:
        self.cancelled = True
        self.abort_event.set()
        self.paused = False
        self._wake.set()

    def interrupt(self) -> None:
        """First call: stop dispatch, let in-flight work finish, keep the rest resumable.
        A second call also aborts in-flight work; unfinished work stays resumable."""
        if self.interrupting:
            self.abort_event.set()
        self.interrupting = True
        self.paused = False
        self._wake.set()

    @property
    def stopping(self) -> bool:
        return self.cancelled or self.interrupting

    def request(self, action: str) -> None:
        if self._loop is None:
            self._early.append(action)  # a signal during setup: applied on bind
        else:
            self._loop.call_soon_threadsafe(getattr(self, action))

    def next_change(self) -> asyncio.Task[bool]:
        """A task that completes at the next control change (pause, resume, cancel,
        interrupt)."""
        self._wake.clear()
        return asyncio.ensure_future(self._wake.wait())

    async def wait_for_change(self, timeout: float) -> None:
        self._wake.clear()
        try:
            await asyncio.wait_for(self._wake.wait(), timeout)
        except TimeoutError:
            pass


@dataclass
class _Item:
    task_key: str
    kind: str  # "execution" | "evaluation"
    case_id: str
    repetition: int
    attempt: int
    binding_hash: str | None = None
    warmup: bool = False


class ResetFailed(Exception):
    """The application could not be reset to the state a case needs (or the run was
    aborted while it was being reset)."""

    def __init__(self, detail: str, *, cancelled: bool = False) -> None:
        super().__init__(detail)
        self.cancelled = cancelled


@dataclass
class RunOutcome:
    state: RunState
    counts: dict[str, dict[str, int]]
    budget: dict[str, Any]
    stop_reason: str | None = None
    warnings: list[str] = field(default_factory=list)


@dataclass
class RunEngine:
    storage: Storage
    artifacts: ArtifactStore
    run_id: str
    plan: ExecutablePlan
    application: ApplicationSpec
    runner: BaseRunner | None  # None when no execution work remains (e.g. resume)
    cases: dict[str, BenchmarkCase]
    metrics: list[ResolvedMetric]
    scoring_id: str
    ledger: BudgetLedger
    controller: RunController
    rng: random.Random
    heartbeat: Callable[[], bool] = lambda: True  # refresh the run lease; False if lost
    run_control: Callable[[], RunControlState | None] = lambda: None
    # State between cases (§7): "none", "per_case" (reset before every attempt) or
    # "per_episode" (reset before an episode's first turn; turns run in order and share
    # state). The engine resets with the selected test world's seed.
    reset_mode: str = "none"
    world_id: str | None = None
    world_seed: Any = None
    # The dependency identity frozen by the run; every engine result must carry it.
    dependency_lock_hash: str | None = None
    # Opt-in caches (16-T3): the key parts that are fixed for the run, or None when off.
    execution_cache: dict[str, Any] | None = None
    evaluation_cache_policy: str | None = None
    _exec_cache_keys: dict[str, str] = field(default_factory=dict)
    # Provider-aware quotas (16-T4): consulted before a task is created.
    _gates: list[QuotaGate] = field(default_factory=list)
    _task_gates: dict[asyncio.Task[Any], list[QuotaGate]] = field(default_factory=dict)
    _throttled: bool = False
    _episodes: dict[str, list[str]] = field(default_factory=dict)  # episode -> turn case IDs
    _episode_of: dict[str, str] = field(default_factory=dict)
    _succeeded_here: set[str] = field(default_factory=set)  # execution keys, this session
    _exec_queue: deque[_Item] = field(default_factory=deque)
    _warmup_queue: deque[_Item] = field(default_factory=deque)
    _eval_queue: deque[_Item] = field(default_factory=deque)
    _delayed: list[tuple[float, int, _Item]] = field(default_factory=list)
    _in_flight: dict[asyncio.Task[Any], _Item] = field(default_factory=dict)
    _waiting_evals: dict[str, list[_Item]] = field(default_factory=dict)  # by execution key
    _executions: dict[str, ExecutionResult | None] = field(default_factory=dict)
    _exec_states: dict[str, WorkItemState] = field(default_factory=dict)
    _scorers: dict[str, BindingScorer] = field(default_factory=dict)
    _reserved: set[str] = field(default_factory=set)
    _seq: itertools.count[int] = field(default_factory=itertools.count)
    _stop_reason: str | None = None
    _last_heartbeat: float = field(default_factory=time.monotonic)
    _last_control_sequence: int = 0
    # Start the reported wall time with the budget ledger, before resume identity and
    # runner setup, so replayed session time matches what hard wall limits consumed.
    _session_started: float = field(default_factory=time.monotonic)
    warnings: list[str] = field(default_factory=list)

    # ------------------------------------------------------------------ setup

    def _event(self, event_type: str, **payload: Any) -> None:
        self.storage.append_run_event(self.run_id, event_type, payload)

    def _transition(
        self,
        item: _Item,
        from_states: set[WorkItemState],
        to: WorkItemState,
        *,
        attempt: int | None = None,
        error: str | None = None,
    ) -> bool:
        updated = self.storage.transition_work_item(
            self.run_id,
            item.task_key,
            from_states=from_states,
            to_state=to,
            attempt=attempt,
            last_error=error,
        )
        if updated is None:
            return False
        self._event(
            "item_state",
            task_key=item.task_key,
            state=to.value,
            attempt=updated.attempt,
            reason=error,
        )
        return True

    def _load(self) -> None:
        by_binding = {m.binding_hash[7:23]: m.binding_hash for m in self.metrics}
        items = self.storage.list_work_items(self.run_id)
        executions: dict[str, ExecutionResult] = {}
        for e in self.storage.list_execution_attempts(self.run_id):
            key = execution_key(e.case_id, e.repetition_id)
            if key not in executions or e.attempt_id > executions[key].attempt_id:
                executions[key] = e
        order = {case_id: i for i, case_id in enumerate(self.cases)}
        pending_evals: list[_Item] = []
        for w in sorted(items, key=lambda w: w.task_key):
            case_id, repetition, binding_key = parse_work_item_key(w.task_key, w.kind)
            item = _Item(
                w.task_key,
                w.kind,
                case_id,
                repetition,
                w.attempt,
                by_binding.get(binding_key) if binding_key else None,
                w.warmup,
            )
            if w.kind == "execution":
                self._exec_states[w.task_key] = w.state
                self._executions[w.task_key] = executions.get(w.task_key)
                if w.state is WorkItemState.PENDING:
                    (self._warmup_queue if item.warmup else self._exec_queue).append(item)
            elif w.state is WorkItemState.PENDING:
                pending_evals.append(item)
        if self.reset_mode == "per_episode":
            # An episode is the cases sharing a group_id, in dataset order; a case without
            # one is an episode of its own. Each (episode, repetition) runs contiguously.
            for case_id, case in self.cases.items():
                episode = case.group_id or case_id
                self._episode_of[case_id] = episode
                self._episodes.setdefault(episode, []).append(case_id)
            first = {ep: order.get(turns[0], 0) for ep, turns in self._episodes.items()}
            sort_key = lambda i: (
                first[self._episode_of[i.case_id]], i.repetition, order.get(i.case_id, 0)
            )
            self._exec_queue = deque(sorted(self._exec_queue, key=sort_key))
            self._warmup_queue = deque(sorted(self._warmup_queue, key=sort_key))
        else:
            self._exec_queue = deque(
                sorted(self._exec_queue, key=lambda i: (order.get(i.case_id, 0), i.repetition))
            )
            self._warmup_queue = deque(
                sorted(
                    self._warmup_queue,
                    key=lambda i: (order.get(i.case_id, 0), i.repetition),
                )
            )
        for item in sorted(
            pending_evals, key=lambda i: (order.get(i.case_id, 0), i.repetition, i.task_key)
        ):
            if self._exec_states.get(execution_key(item.case_id, item.repetition)) in TERMINAL:
                self._eval_queue.append(item)
            else:
                self._waiting_evals.setdefault(
                    execution_key(item.case_id, item.repetition), []
                ).append(item)

    # ------------------------------------------------------------------ main loop

    async def execute(self) -> RunOutcome:
        self.controller.bind(asyncio.get_running_loop())
        self._gates = [QuotaGate(q) for q in self.plan.quotas]
        self._load()
        self._set_state(RunState.RUNNING)
        self._event(
            "run_session_started",
            pending_executions=len(self._exec_queue) + len(self._warmup_queue),
            pending_evaluations=len(self._eval_queue) + sum(map(len, self._waiting_evals.values())),
        )
        needs_runner = bool(self._exec_queue or self._warmup_queue) and not self.controller.cancelled
        try:
            if needs_runner:
                assert self.runner is not None, "execution work remains but no runner was given"
                await self._while_starting(self.runner.prepare())
            await self._while_starting(self._open_scorers())
            await self._loop()
        finally:
            await self._shutdown(needs_runner)
        return self._finish()

    async def _while_starting(self, work: Awaitable[_T]) -> _T:
        """Await start-up work (runner preparation, evaluator start-up) while keeping the
        committed state in step with controls. A pause or cancel requested meanwhile shows
        as `pausing`/`cancelling` at once (section 15), not only once start-up has ended;
        nothing is dispatched until it has."""
        task = asyncio.ensure_future(work)
        try:
            while True:
                self._sync_run_control()
                # Armed first: a change before this line is in the state recorded next,
                # and one after it wakes the wait.
                change = self.controller.next_change()
                self._set_state(self._busy_state())
                done, _ = await asyncio.wait(
                    {task, change},
                    timeout=_CONTROL_POLL_SECONDS,
                    return_when=asyncio.FIRST_COMPLETED,
                )
                if change not in done:
                    change.cancel()
                if task.done():
                    return task.result()
        except BaseException:
            task.cancel()
            raise

    async def _open_scorers(self) -> None:
        wanted = {i.binding_hash for i in self._eval_queue} | {
            i.binding_hash for items in self._waiting_evals.values() for i in items
        }
        for metric in self.metrics:
            if metric.binding_hash in wanted:
                scorer = BindingScorer(
                    self.storage,
                    self.artifacts,
                    self.scoring_id,
                    metric,
                    self.plan.model_evaluation_timeout_seconds
                    if metric.manifest.uses_models
                    else self.plan.evaluation_timeout_seconds,
                    self.controller.abort_event,
                    application=self.application,
                    dependency_lock_hash=self.dependency_lock_hash,
                    episodes=episode_prefixes(self.cases.values()),
                )
                scorer.cache_policy_hash = self.evaluation_cache_policy
                await scorer.open()
                self._scorers[metric.binding_hash] = scorer

    def _keep_lease(self) -> None:
        self._sync_run_control()
        now = time.monotonic()
        if now - self._last_heartbeat < _HEARTBEAT_SECONDS:
            return
        self._last_heartbeat = now
        if not self.heartbeat() and not self.controller.interrupting:
            self.warnings.append("run lease lost to another session; stopped dispatching")
            self.controller.interrupt()

    def _sync_run_control(self) -> None:
        state = self.run_control()
        if state is None or state.sequence <= self._last_control_sequence:
            return
        action = {"running": "resume", "paused": "pause", "cancelled": "cancel"}[
            state.desired_state
        ]
        if self.controller.cancelled and action != "cancel":
            return
        if self.controller.abort_event.is_set() and action != "cancel":
            # A second interrupt has already aborted in-flight work. Keep the durable
            # request for the next resumable session instead of claiming it was applied.
            return
        getattr(self.controller, action)()
        self._last_control_sequence = state.sequence
        self._event(
            "run_control_applied",
            control_sequence=state.sequence,
            desired_state=state.desired_state,
        )

    async def _loop(self) -> None:
        ctl = self.controller
        while True:
            self._keep_lease()
            self._throttled = False
            if ctl.cancelled:
                self._drain_delayed()  # waiting retries are cancelled, not stranded
            self._release_due_retries()
            stopping = ctl.stopping
            if not stopping and not ctl.paused:
                self._dispatch_executions()
            if not ctl.paused:
                await self._dispatch_evaluations(stopping)
            if self._in_flight:
                self._set_state(self._busy_state())
                done, _ = await asyncio.wait(
                    set(self._in_flight),
                    timeout=self._next_wait(),
                    return_when=asyncio.FIRST_COMPLETED,
                )
                for task in done:
                    await self._complete(task, self._in_flight.pop(task))
                continue
            # Nothing in flight.
            if ctl.paused and not stopping:
                self._set_state(RunState.PAUSED)
                await ctl.wait_for_change(_POLL_SECONDS * 5)
                continue
            if self._throttled:
                # A quota's rate or cooldown holds the next work back: it waits as a queue
                # entry, and the loop stays responsive to controls meanwhile. (A cancelled
                # run consults no quota, so this never delays a cancel.)
                await ctl.wait_for_change(_POLL_SECONDS)
                continue
            if self._delayed and not stopping:
                await ctl.wait_for_change(self._next_wait())
                continue
            if self._settle_undispatchable(stopping):
                continue  # newly unblocked evaluations to record
            if not self._eval_queue:
                return

    def _busy_state(self) -> RunState:
        ctl = self.controller
        if ctl.cancelled:
            return RunState.CANCELLING
        if ctl.interrupting:
            return RunState.INTERRUPTING
        return RunState.PAUSING if ctl.paused else RunState.RUNNING

    def _next_wait(self) -> float:
        if not self._delayed:
            return _POLL_SECONDS
        return max(0.0, min(_POLL_SECONDS, self._delayed[0][0] - time.monotonic()))

    def _drain_delayed(self) -> None:
        while self._delayed:
            _, _, item = heapq.heappop(self._delayed)
            self._queue_for(item).append(item)

    def _release_due_retries(self) -> None:
        now = time.monotonic()
        while self._delayed and self._delayed[0][0] <= now:
            _, _, item = heapq.heappop(self._delayed)
            self._queue_for(item).appendleft(item)

    def _queue_for(self, item: _Item) -> deque[_Item]:
        if item.kind != "execution":
            return self._eval_queue
        return self._warmup_queue if item.warmup else self._exec_queue

    def _warmups_pending(self) -> bool:
        return bool(self._warmup_queue) or any(
            item.kind == "execution" and item.warmup
            for _, _, item in self._delayed
        ) or any(
            item.kind == "execution" and item.warmup
            for item in self._in_flight.values()
        )

    # ------------------------------------------------------------------ dispatch

    def _dispatch_executions(self) -> None:
        while self._running("execution") < self.plan.concurrency.application:
            if self._warmup_queue:
                queue = self._warmup_queue
            elif self._warmups_pending():
                return  # global warmup barrier: no measured call starts before warmups settle
            else:
                queue = self._exec_queue
            if not queue:
                return
            if self._stop_reason is not None:
                return
            gates = self._gates_for("execution")
            if self._held(gates):
                return
            denial = self.ledger.reserve_application()
            if denial is not None:
                self._stop_reason = denial
                self._event("budget_exhausted", reason=denial)
                return
            gate = self._episode_gate(queue[0])
            if gate is not None:
                self.ledger.settle_application(dispatched=False, cost=None)
                self._block_undispatched(queue.popleft(), gate)
                continue
            item = queue.popleft()
            item.attempt += 1
            if not self._transition(
                item, {WorkItemState.PENDING}, WorkItemState.RUNNING, attempt=item.attempt
            ):
                self.ledger.settle_application(dispatched=False, cost=None)
                continue
            task = asyncio.ensure_future(self._reset_then_invoke(item))
            self._in_flight[task] = item
            self._start(task, gates)

    def _is_first_turn(self, item: _Item) -> bool:
        return self._episodes[self._episode_of[item.case_id]][0] == item.case_id

    def _episode_gate(self, item: _Item) -> str | None:
        """Why a later episode turn must not run: the turn before it did not succeed in
        this session, so the application's state is not what the episode built."""
        if self.reset_mode != "per_episode" or self._is_first_turn(item):
            return None
        episode = self._episode_of[item.case_id]
        turns = self._episodes[episode]
        previous = execution_key(turns[turns.index(item.case_id) - 1], item.repetition)
        if previous in self._succeeded_here:
            return None
        state = self._exec_states.get(previous)
        if state is WorkItemState.SUCCEEDED:
            return (
                f"episode_interrupted: episode {episode!r} stopped before this turn; the state "
                "its earlier turns built cannot be restored"
            )
        return (
            f"episode_broken: an earlier turn of episode {episode!r} did not succeed "
            f"({state.value if state else 'not run'})"
        )

    async def _reset_or_abort(self) -> ResetReport:
        """The runner's reset, abandoned (and its process cleaned up) as soon as the run is
        aborted, like an invocation."""
        assert self.runner is not None
        reset = asyncio.ensure_future(self.runner.reset(self.world_seed))
        if await race(reset, timeout=_RESET_WAIT_SECONDS, cancel=self.controller.abort_event) != (
            "cancelled"
        ):
            return await reset
        reset.cancel()
        await asyncio.gather(reset, return_exceptions=True)
        return ResetReport("aborted", "the run was aborted during the reset")

    def _cached_execution(self, item: _Item) -> ExecutionResult | None:
        assert self.execution_cache is not None
        key = cache.execution_key(self.cases[item.case_id], item.repetition, **self.execution_cache)
        self._exec_cache_keys[item.task_key] = key
        entry = self.storage.get_cache_entry("execution", key)
        source = self.storage.get_execution_attempt(entry[1]) if entry else None
        if source is None or source.status is not ExecutionStatus.OK:
            return None
        copy = cache.execution_from_cache(
            source, run_id=self.run_id, repetition=item.repetition, attempt=item.attempt, key=key
        )
        self.storage.commit_execution_attempt(copy)
        self._event(
            "cache_hit",
            task_key=item.task_key,
            kind="execution",
            source=entry[1] if entry else None,
        )
        return copy

    def _block_undispatched(self, item: _Item, reason: str) -> None:
        if self._transition(item, {WorkItemState.PENDING}, WorkItemState.BLOCKED, error=reason):
            self._exec_states[item.task_key] = WorkItemState.BLOCKED
            self._eval_queue.extend(self._waiting_evals.pop(item.task_key, []))

    async def _reset_then_invoke(self, item: _Item) -> ExecutionResult:
        """Reset the application first when this attempt needs a known state, then invoke.
        A reset that fails raises ResetFailed: the case is not run on unknown state. With
        the execution cache on, a stored result for the same key is copied instead: nothing
        is reset or invoked."""
        assert self.runner is not None
        is_warmup = item.warmup
        if self.execution_cache is not None and not is_warmup:
            cached = self._cached_execution(item)
            if cached is not None:
                return cached
        if self.reset_mode == "per_case" or (
            self.reset_mode == "per_episode" and self._is_first_turn(item)
        ):
            report = await self._reset_or_abort()
            self._event(
                "app_reset",
                task_key=item.task_key,
                episode=self._episode_of.get(item.case_id),
                world=self.world_id,
                status=report.status,
                detail=report.detail,
            )
            if report.status == "aborted":
                raise ResetFailed(report.detail, cancelled=True)
            if report.status not in ("reset", "not_needed"):
                raise ResetFailed(report.detail)
        return await invoke_and_record(
            self.runner,
            self.cases[item.case_id],
            storage=self.storage,
            artifacts=self.artifacts,
            run_id=self.run_id,
            repetition_id=item.repetition,
            attempt_id=item.attempt,
            warmup=is_warmup,
            cancel=self.controller.abort_event,
        )

    async def _dispatch_evaluations(self, stopping: bool) -> None:
        if stopping and not self.controller.cancelled:
            return  # interrupt: unstarted evaluations stay pending for resume
        # Work held by one evaluator's quota does not hold back other evaluators or
        # records that need no evaluator: up to _HELD_SCAN held entries are looked past,
        # and put back in order.
        held_back: list[_Item] = []
        held_evaluators: set[str] = set()
        try:
            await self._dispatch_evaluations_past(held_back, held_evaluators)
        finally:
            self._eval_queue.extendleft(reversed(held_back))

    async def _dispatch_evaluations_past(
        self, held_back: list[_Item], held_evaluators: set[str]
    ) -> None:
        while self._eval_queue and self._running("evaluation") < self.plan.concurrency.evaluation:
            if len(held_back) >= _HELD_SCAN:
                return
            item = self._eval_queue.popleft()
            if self.controller.cancelled and (
                item.binding_hash is None or item.binding_hash not in self._scorers
            ):
                self._transition(
                    item,
                    {WorkItemState.PENDING},
                    WorkItemState.CANCELLED,
                    error="run cancelled before evaluation",
                )
                continue
            assert item.binding_hash is not None
            scorer = self._scorers[item.binding_hash]
            exec_key = execution_key(item.case_id, item.repetition)
            execution = self._executions.get(exec_key)
            exec_state = self._exec_states.get(exec_key)
            needs_evaluator = exec_state is WorkItemState.SUCCEEDED and execution is not None
            evaluator_id = scorer.manifest.evaluator_id
            gates = (
                self._gates_for("evaluation", evaluator_id)
                if needs_evaluator and not self.controller.cancelled
                else []
            )
            if gates and (evaluator_id in held_evaluators or self._held(gates)):
                self._throttled = True
                held_evaluators.add(evaluator_id)
                held_back.append(item)
                continue
            if needs_evaluator and self.controller.cancelled:
                self._record_without_evaluator(item, scorer, "cancelled", ExecutionStatus.CANCELLED)
                continue
            if needs_evaluator:
                denial = self.ledger.reserve_evaluation()
                if denial is not None:
                    if self._stop_reason is None:
                        self._stop_reason = denial
                        self._event("budget_exhausted", reason=denial)
                    self._record_without_evaluator(item, scorer, f"not_evaluated:{denial}")
                    continue
                self._reserved.add(item.task_key)
            item.attempt += 1
            if not self._transition(
                item, {WorkItemState.PENDING}, WorkItemState.RUNNING, attempt=item.attempt
            ):
                self._release_evaluation(item)
                continue
            if execution is None:
                self._finish_missing(
                    item, scorer, f"not_executed:{(exec_state or WorkItemState.BLOCKED).value}"
                )
                continue
            task = asyncio.ensure_future(scorer.score(execution, [self.cases[item.case_id]]))
            self._in_flight[task] = item
            self._start(task, gates)

    def _gates_for(self, kind: str, evaluator_id: str | None = None) -> list[QuotaGate]:
        return [g for g in self._gates if g.applies_to(kind, evaluator_id)]

    def _held(self, gates: list[QuotaGate]) -> bool:
        """Whether a quota holds the next work back (rate, cap or cooldown)."""
        if any(g.wait_seconds() > 0 for g in gates):
            self._throttled = True
            return True
        return False

    def _start(self, task: asyncio.Task[Any], gates: list[QuotaGate]) -> None:
        for gate in gates:
            gate.start()
        if gates:
            self._task_gates[task] = gates

    def _running(self, kind: str) -> int:
        return sum(1 for i in self._in_flight.values() if i.kind == kind)

    def _release_evaluation(self, item: _Item) -> None:
        if item.task_key in self._reserved:
            self._reserved.discard(item.task_key)
            self.ledger.settle_evaluation(None)

    def _record_without_evaluator(
        self,
        item: _Item,
        scorer: BindingScorer,
        reason: str,
        status: ExecutionStatus = ExecutionStatus.SKIPPED,
    ) -> None:
        item.attempt += 1
        if self._transition(
            item, {WorkItemState.PENDING}, WorkItemState.RUNNING, attempt=item.attempt
        ):
            self._finish_missing(item, scorer, reason, status)

    def _finish_missing(
        self,
        item: _Item,
        scorer: BindingScorer,
        reason: str,
        status: ExecutionStatus = ExecutionStatus.SKIPPED,
    ) -> None:
        execution = self._executions.get(execution_key(item.case_id, item.repetition))
        target = MissingExecution(
            self.run_id,
            item.case_id,
            item.repetition,
            execution.execution_id if execution else None,
        )
        result = scorer.score_missing(target, reason, status=status)
        scorer.finalize(result)
        final = (
            WorkItemState.CANCELLED
            if status is ExecutionStatus.CANCELLED
            else WorkItemState.SUCCEEDED
        )
        self._transition(
            item,
            {WorkItemState.RUNNING},
            final,
            error=None if final is WorkItemState.SUCCEEDED else reason,
        )

    # ------------------------------------------------------------------ completion

    async def _complete(self, task: asyncio.Task[Any], item: _Item) -> None:
        gates = self._task_gates.pop(task, [])
        for gate in gates:
            gate.finish()
        if item.kind == "execution":
            await self._complete_execution(task, item)
            self._backpressure(task, gates)
        else:
            self._complete_evaluation(task, item)

    def _backpressure(self, task: asyncio.Task[Any], gates: list[QuotaGate]) -> None:
        """A provider's "slow down" (HTTP 429 or 503) pauses every quota the call ran
        under, for its Retry-After or the quota's backoff."""
        if not gates or task.cancelled() or task.exception() is not None:
            return
        result = task.result()
        status, retry_after = http_status(result)
        if status not in (429, 503):
            return
        for gate in gates:
            pause = gate.backpressure(retry_after)
            self._event("backpressure", quota=gate.quota.name, status=status, pause_seconds=pause)

    async def _complete_execution(self, task: asyncio.Task[Any], item: _Item) -> None:
        key = self._exec_cache_keys.pop(item.task_key, None)  # released on every path
        try:
            result: ExecutionResult = task.result()
        except ResetFailed as exc:
            # Never invoked: the application was not in the state the case needs.
            self.ledger.settle_application(dispatched=False, cost=None)
            if exc.cancelled:
                self._final_execution(
                    item, WorkItemState.CANCELLED, "cancelled before the case ran", None
                )
            else:
                self._final_execution(
                    item, WorkItemState.BLOCKED, f"reset_failed: {exc}"[:500], None
                )
            return
        except Exception as exc:  # noqa: BLE001 - an engine-side failure, recorded not raised
            self.ledger.settle_application(dispatched=True, cost=None)
            if is_storage_failure(exc):
                self._stop_for_storage(item, exc)
                return
            self._final_execution(
                item, WorkItemState.FAILED, f"engine_error:{type(exc).__name__}: {exc}"[:500], None
            )
            return
        self.ledger.settle_application(dispatched=was_dispatched(result), cost=result.cost)
        if key is not None and result.status is ExecutionStatus.OK and not result.cache:
            self.storage.put_cache_entry("execution", key, self.run_id, result.execution_id)
        if not result.cache and (result.cost is not None or result.usage is not None):
            # A cache hit spent nothing now: its source run already recorded the spend.
            self.storage.commit_usage_event(
                UsageEvent(
                    usage_event_id=f"{result.execution_id}:usage",
                    run_id=self.run_id,
                    role=UsageRole.APPLICATION,
                    provider=None,
                    tokens=result.usage,
                    calls=1,
                    cost=result.cost,
                )
            )
        verdict = classify_execution(result)
        ctl = self.controller
        stopping = ctl.stopping
        if (
            ctl.interrupting
            and not ctl.cancelled
            and verdict.final_state is WorkItemState.CANCELLED
        ):
            # Aborted by a second interrupt with no effect possible: effect-free work stays
            # resumable. (An ambiguous effectful abort is UNKNOWN_EFFECT, handled below.)
            self._transition(
                item,
                {WorkItemState.RUNNING},
                WorkItemState.PENDING,
                error="aborted by interrupt; safe to repeat (no effects)",
            )
            return
        if verdict.retry and item.attempt < self.plan.retry.max_attempts:
            if stopping and ctl.cancelled:
                self._final_execution(
                    item,
                    WorkItemState.CANCELLED,
                    f"cancelled before retrying: {verdict.reason}",
                    result,
                )
                return
            delay = backoff_delay(
                self.plan.retry, item.attempt, self.rng, verdict.retry_after_seconds
            )
            if self._transition(
                item, {WorkItemState.RUNNING}, WorkItemState.PENDING, error=verdict.reason
            ):
                self._event(
                    "retry_scheduled",
                    task_key=item.task_key,
                    attempt=item.attempt,
                    delay_seconds=round(delay, 3),
                )
                if stopping:  # interrupt: leave it pending for resume
                    return
                heapq.heappush(self._delayed, (time.monotonic() + delay, next(self._seq), item))
            return
        reason = verdict.reason if verdict.final_state is not WorkItemState.SUCCEEDED else None
        if verdict.retry:
            reason = f"{verdict.reason} (retries exhausted after {item.attempt} attempts)"
        self._final_execution(item, verdict.final_state, reason, result)

    def _final_execution(
        self, item: _Item, state: WorkItemState, reason: str | None, result: ExecutionResult | None
    ) -> None:
        self._transition(item, {WorkItemState.RUNNING}, state, error=reason)
        if state is WorkItemState.SUCCEEDED:
            self._succeeded_here.add(item.task_key)
        self._exec_states[item.task_key] = state
        self._executions[item.task_key] = result
        self._eval_queue.extend(self._waiting_evals.pop(item.task_key, []))

    def _stop_for_storage(self, item: _Item, exc: BaseException) -> None:
        """The workspace can't take writes (disk full, I/O error, ...). That is not a result
        of this item: leave it `running`, exactly as a crash would, and stop dispatching.
        Resume's recovery then counts a possibly dispatched call and repeats it only if the
        application declares no effects."""
        warning = (
            f"workspace storage failed ({type(exc).__name__}: {exc}); stopped dispatching. "
            f"Free space or fix the workspace, then resume the run"
        )
        if warning not in self.warnings:
            self.warnings.append(warning[:500])
        if not self.controller.interrupting:
            # A second interrupt means "abort what is in flight"; another storage failure,
            # or one after the user's first Ctrl+C, must not escalate to that.
            self.controller.interrupt()

    def _complete_evaluation(self, task: asyncio.Task[Any], item: _Item) -> None:
        assert item.binding_hash is not None
        scorer = self._scorers[item.binding_hash]
        try:
            result = task.result()
        except BaseException as exc:  # noqa: BLE001 - includes cancellation of the task
            self._release_evaluation(item)
            if is_storage_failure(exc):
                self._stop_for_storage(item, exc)
                return
            status = (
                ExecutionStatus.CANCELLED
                if isinstance(exc, asyncio.CancelledError)
                else ExecutionStatus.ERROR
            )
            self._finish_missing(item, scorer, f"engine_error:{type(exc).__name__}", status)
            return
        if item.task_key in self._reserved:
            self._reserved.discard(item.task_key)
            self.ledger.settle_evaluation(dict(result.resources))
        verdict = classify_evaluation(result, scorer.manifest)
        ctl = self.controller
        if (
            ctl.interrupting
            and not ctl.cancelled
            and (verdict.retry or result.status is ExecutionStatus.CANCELLED)
        ):
            # Interrupted: a transient or aborted evaluation is not a final result; it runs
            # again on resume (its spend stays recorded as an attempt).
            self._transition(
                item, {WorkItemState.RUNNING}, WorkItemState.PENDING, error=verdict.reason
            )
            return
        if verdict.retry and item.attempt < self.plan.retry.max_attempts and not ctl.stopping:
            delay = backoff_delay(self.plan.retry, item.attempt, self.rng)
            if self._transition(
                item, {WorkItemState.RUNNING}, WorkItemState.PENDING, error=verdict.reason
            ):
                self._event(
                    "retry_scheduled",
                    task_key=item.task_key,
                    attempt=item.attempt,
                    delay_seconds=round(delay, 3),
                )
                heapq.heappush(self._delayed, (time.monotonic() + delay, next(self._seq), item))
            return
        scorer.finalize(result)
        reason = None if verdict.final_state is WorkItemState.SUCCEEDED else verdict.reason
        if verdict.retry:
            reason = f"{verdict.reason} (retries exhausted after {item.attempt} attempts)"
        self._transition(item, {WorkItemState.RUNNING}, verdict.final_state, error=reason)

    # ------------------------------------------------------------------ stopping

    def _settle_undispatchable(self, stopping: bool) -> bool:
        """Nothing is in flight. Decide what happens to work that can no longer be
        dispatched; returns True if evaluations were released for recording."""
        if self.controller.interrupting and not self.controller.cancelled:
            self._exec_queue.clear()  # unstarted work stays pending for resume
            self._warmup_queue.clear()
            self._eval_queue.clear()
            self._delayed.clear()
            return False
        if not self._exec_queue and not self._warmup_queue:
            return False
        if self.controller.cancelled:
            state, reason = WorkItemState.CANCELLED, "run cancelled before dispatch"
        elif self._stop_reason is not None:
            state, reason = WorkItemState.BLOCKED, f"budget: {self._stop_reason}"
        else:
            return False
        for queue in (self._warmup_queue, self._exec_queue):
            while queue:
                item = queue.popleft()
                if self._transition(item, {WorkItemState.PENDING}, state, error=reason):
                    self._exec_states[item.task_key] = state
                    self._eval_queue.extend(self._waiting_evals.pop(item.task_key, []))
        return True

    async def _shutdown(self, needs_runner: bool) -> None:
        for task in list(self._in_flight):
            task.cancel()
        if self._in_flight:
            await asyncio.gather(*self._in_flight, return_exceptions=True)
        for scorer in self._scorers.values():
            await scorer.close(self.warnings)
        if needs_runner and self.runner is not None:
            await self.runner.close()

    def _set_state(self, state: RunState) -> None:
        if self.controller.state is not state:
            self.controller.state = state
            self.storage.update_run_status(self.run_id, state.value)

    def _finish(self) -> RunOutcome:
        ctl = self.controller
        pending = any(
            w.state in (WorkItemState.PENDING, WorkItemState.RUNNING)
            for w in self.storage.list_work_items(self.run_id)
        )
        if ctl.cancelled:
            state = RunState.CANCELLED
        elif ctl.interrupting or pending:
            state = RunState.INTERRUPTED
        elif self._stop_reason is not None:
            state = RunState.BUDGET_EXHAUSTED
        else:
            state = RunState.COMPLETED
        self._set_state(state)
        counts = work_counts(self.storage, self.run_id)
        budget = self.ledger.summary()
        self._event(
            "run_session_ended",
            state=state.value,
            counts=counts,
            session_elapsed_seconds=round(time.monotonic() - self._session_started, 3),
            budget=budget,
            stop_reason=self._stop_reason,
            warnings=self.warnings,
            quotas=[g.summary() for g in self._gates],
        )
        return RunOutcome(state, counts, budget, self._stop_reason, list(self.warnings))


_STORAGE_ERRNOS = frozenset(
    code
    for code in (
        errno.ENOSPC,
        getattr(errno, "EDQUOT", None),
        errno.EIO,
        errno.EROFS,
    )
    if code is not None
)


# Windows codes whose errno mapping is too generic to use: ERROR_WRITE_PROTECT (19, maps to
# EACCES), ERROR_HANDLE_DISK_FULL (39, EINVAL), ERROR_DISK_FULL (112, ENOSPC).
_STORAGE_WINERRORS = frozenset({19, 39, 112})
# SQLite primary result codes: READONLY, IOERR, FULL. Not BUSY/LOCKED (contention) and not
# CONSTRAINT (a bug): those are not the workspace running out of room.
_STORAGE_SQLITE_CODES = frozenset({8, 10, 13})


def is_storage_failure(exc: BaseException) -> bool:
    """Whether `exc` means the workspace itself can't take writes, rather than something
    wrong with one work item: a full disk or quota, an I/O error, or a read-only
    filesystem, whether reported by the OS or by the run database."""
    if isinstance(exc, sqlite3.DatabaseError):
        code = getattr(exc, "sqlite_errorcode", None)
        return code is not None and code & 0xFF in _STORAGE_SQLITE_CODES
    if not isinstance(exc, OSError):
        return False
    return exc.errno in _STORAGE_ERRNOS or getattr(exc, "winerror", None) in _STORAGE_WINERRORS


_NEVER_DISPATCHED = frozenset(
    {ErrorKind.BINDING, ErrorKind.REQUEST_LIMIT, ErrorKind.POLICY_DENIED, ErrorKind.SPAWN_FAILED}
)


def was_dispatched(result: ExecutionResult) -> bool:
    """Whether the call reached the application (and so counts against the call budget).
    `effect_state` alone cannot say: effect-free apps report `none_declared` either way."""
    if result.effect_state is EffectState.NOT_DISPATCHED:
        return False
    return result.error_kind not in _NEVER_DISPATCHED


def work_counts(storage: Storage, run_id: str) -> dict[str, dict[str, int]]:
    counts: dict[str, dict[str, int]] = {}
    for item in storage.list_work_items(run_id):
        kind = counts.setdefault(item.kind, {})
        kind[item.state.value] = kind.get(item.state.value, 0) + 1
    return counts
